- name: variables
  hosts: localhost
  vars:
   Course: "ansible"
   Trainer: "online"
   Duration: "120 hrs"
  tasks:
  - name: printing the info
    ansible.builtin.debug:
     msg: "Hello i'm learning {{Course}} from {{Trainer}} and duration is {{Duration}}"