- name: using variables from other files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: "printing info"
    ansible.builtin.debug:
     msg: "hello i'm learning {{Course}} from {{Trainer}} for {{Duration}}"