- name : Working with filters
  hosts: web
  tasks:
  - name: printing the info
    ansible.builtin.debug:
     msg: "hello i'm learning {{Course | default('Ansible')}}"

- name : upper-case
  hosts: web
  vars:
   greet: "Hello revanth"
  tasks:
  - name: print upper case
    ansible.builtin.debug:
     msg: "{{greet | upper }}" 

  - name : lower-case
    hosts: web
    vars:
     greet: "Hello revanth"
    tasks:
     - name: print lower case
       ansible.builtin.debug:
        msg: "{{greet | lower }}" 